apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: birthday-app
spec:
  replicas: 1
  template:
    metadata:
      name: birthday-app      
      labels:
        app: birthday-app
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: birthday-app-vol
        gcePersistentDisk:
          pdName: birthday-app-vol-1
          fsType: ext4
      containers:
      - name:  birthday-app
        image: docker.io/chanalex/birthday-app:0.4
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
        env:
        - name: APP_LOG
          value: /disk/app.log
        - name: DATABASE_URI
          value:  'sqlite:////disk/data.db'
        volumeMounts:
        - name: birthday-app-vol
          mountPath: /disk
        ports:
            - name: app-port
              containerPort: 5000
