apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: birthday-app
spec:
  replicas: 1
  template:
    metadata:
      name: birthday-app      
      labels:
        app: birthday-app
    spec:
      containers:
      - name:  birthday-app
        image: docker.io/chanalex/birthday-app:0.1
        livenessProbe:
          httpGet:
            path: hello/liveness
            port: 5000
        ports:
            - name: app-port
              containerPort: 5000
